### ISSUE TITLE
Chart display switches

### ISSUE THREAD

**Issue by TenchMaviatorius2759** [Akylas/oss-weather#195]
I have a suggestion.
First of all, I wanted to ask. Is it supposed to be that the options "Force charts to show in landscape" and "Charts use full height in portrait" can be enabled simultaneously? In this case, only one function will work.
I would like to make them mutually exclusive, meaning that turning on one of them turns off the other and vice versa, to avoid confusion.
![Screenshot_20240603-210951_OSS Погода](https://github.com/Akylas/oss-weather/assets/140940260/92ab0cc2-b57e-434b-85eb-3a936efb2df5)

v2.5.0.124 Android 13

**Comment by farfromrefug** [comment]
@TenchMaviatorius2759 I see what you mean. The thing is you need to see it that way:
* you always enable chart use full height
* sometimes you want to enable auto landscape.
It was exclusive then everytime you enable auto landscape it would disable full height. So if you were to disable auto landscape you would have to enable full height. So it would require 2 taps instead of one.

I do understand your point though as indeed as a matter of fact they cant be both used together (well auto landscape will take over and thus the other one is useless), however i dont think it hurts to have both enabled at the same time, and as i mentioned before it prevents unwanted behaviors.

is that ok with you? I am open to still change the behavior
