### ISSUE TITLE
Mistakes

### ISSUE THREAD

**Issue by TenchMaviatorius2759** [Akylas/oss-weather#206]
There are bugs in version[ 2.6.2.128.](https://github.com/Akylas/oss-weather/releases/tag/android%2Fgithub%2F2.6.2%2F128)
![Screenshot_20240705-181104_OSS Погода](https://github.com/Akylas/oss-weather/assets/140940260/7cac8de8-5635-48e7-9a9a-dc20b6b7d3aa)
![Screenshot_20240705-181405_OSS Погода](https://github.com/Akylas/oss-weather/assets/140940260/2fbf7e68-4a4b-49d5-b8ae-19c37de7b571)

When you click on a chart to bring up a popup window, an error occurs.
There is also an error when changing the theme.

**Comment by farfromrefug** [comment]
@TenchMaviatorius2759 thanks and sorry for that will try to reproduce

**Comment by Mrnofish** [comment]
Also having this issue on LineageOS 20 (A13), provider is Open Meteo, model MET Nordic.

The error dialog is shown whenever I try to open the details for any hourly forecast slot from the main screen.

The problem is new to 2.6.2 Build 128, I guess possibly resulting from this change? 

>more reactive highlight popover on day chart view ([748d79e](https://github.com/Akylas/oss-weather/blob/android/github/2.6.2/128/748d79ebc2037b7ee1f2a9398206bc780329ba83))

I would change the issue title to:

"[2.6.2 Build 128] Opening hourly forecast causes java.lang.Exception in android.view.View".

**Comment by farfromrefug** [comment]
@TenchMaviatorius2759 thanks and sorry for that will try to reproduce@Mrnofish just released a new version
